name: endeavor
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^6.3.0
  firebase_core: ^2.24.0
  google_fonts: ^6.2.1
  carousel_slider: ^5.0.0
  fl_chart: ^1.0.0
  animated_splash_screen: ^1.3.0
  lottie: ^3.3.1
  page_transition: ^2.2.1
  http: ^1.4.0
  charts_flutter: ^0.12.0
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.5.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf
